version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME}:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - '${REDIS_VOLUME}:/bitnami/redis/data'

volumes:
  polls_pg_data:
  polls_redis_data:
